// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// diffChange
arma::mat diffChange(arma::mat adjmat, arma::mat nneighbors, arma::mat conc, arma::vec niter);
RcppExport SEXP _EcoAgents_diffChange(SEXP adjmatSEXP, SEXP nneighborsSEXP, SEXP concSEXP, SEXP niterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type adjmat(adjmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type nneighbors(nneighborsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type conc(concSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type niter(niterSEXP);
    rcpp_result_gen = Rcpp::wrap(diffChange(adjmat, nneighbors, conc, niter));
    return rcpp_result_gen;
END_RCPP
}
// diffChangeVec
arma::mat diffChangeVec(arma::mat adjmat, arma::mat nneighbors, arma::Row<double> conc, int niter);
RcppExport SEXP _EcoAgents_diffChangeVec(SEXP adjmatSEXP, SEXP nneighborsSEXP, SEXP concSEXP, SEXP niterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type adjmat(adjmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type nneighbors(nneighborsSEXP);
    Rcpp::traits::input_parameter< arma::Row<double> >::type conc(concSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    rcpp_result_gen = Rcpp::wrap(diffChangeVec(adjmat, nneighbors, conc, niter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EcoAgents_diffChange", (DL_FUNC) &_EcoAgents_diffChange, 4},
    {"_EcoAgents_diffChangeVec", (DL_FUNC) &_EcoAgents_diffChangeVec, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_EcoAgents(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
