// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// diffuse_arma
arma::sp_mat diffuse_arma(arma::sp_mat A, arma::sp_mat B, int niter);
RcppExport SEXP _EcoAgents_diffuse_arma(SEXP ASEXP, SEXP BSEXP, SEXP niterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    rcpp_result_gen = Rcpp::wrap(diffuse_arma(A, B, niter));
    return rcpp_result_gen;
END_RCPP
}
// trans_
arma::sp_mat trans_(arma::sp_mat X);
RcppExport SEXP _EcoAgents_trans_(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(trans_(X));
    return rcpp_result_gen;
END_RCPP
}
// diffuse_eigen
Eigen::SparseMatrix<double> diffuse_eigen(Eigen::SparseMatrix<double>& A, Eigen::SparseMatrix<double>& B, int niter);
RcppExport SEXP _EcoAgents_diffuse_eigen(SEXP ASEXP, SEXP BSEXP, SEXP niterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    rcpp_result_gen = Rcpp::wrap(diffuse_eigen(A, B, niter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EcoAgents_diffuse_arma", (DL_FUNC) &_EcoAgents_diffuse_arma, 3},
    {"_EcoAgents_trans_", (DL_FUNC) &_EcoAgents_trans_, 1},
    {"_EcoAgents_diffuse_eigen", (DL_FUNC) &_EcoAgents_diffuse_eigen, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_EcoAgents(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
