# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Diffuse
#'
#' @param A Matrix A.
#' @param B Matrix B
#' @param niter
#'
diffuse_arma <- function(A, B, niter) {
    .Call(`_EcoAgents_diffuse_arma`, A, B, niter)
}

#' transpose a sparse matrix
#'
#' @param X Matrix A.
#'
trans_ <- function(X) {
    .Call(`_EcoAgents_trans_`, X)
}

#' Diffuse Eigen
#'
#' @param A Matrix A.
#' @param B Matrix B
#' @param niter
#'
diffuse_eigen <- function(A, B, niter) {
    .Call(`_EcoAgents_diffuse_eigen`, A, B, niter)
}

