# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply two sparse matrices
#'
#' @param A Matrix A.
#' @param B Matrix B
#'
#' @export
multiply <- function(A, B) {
    .Call(`_EcoAgents_multiply`, A, B)
}

#' transpose a sparse matrix
#'
#' @param X Matrix A.
#'
#' @export
trans_ <- function(X) {
    .Call(`_EcoAgents_trans_`, X)
}

trace_ <- function(X) {
    .Call(`_EcoAgents_trace_`, X)
}

